CRITICAL - 2021-09-28 11:00:52 --> Invalid file: header.php
#0 C:\xampp\htdocs\opacko\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('header.php')
#1 C:\xampp\htdocs\opacko\system\Common.php(1097): CodeIgniter\View\View->render('header', Array, true)
#2 C:\xampp\htdocs\opacko\app\Controllers\Home.php(9): view('header')
#3 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): App\Controllers\Home->index()
#4 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\opacko\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-28 11:33:05 --> Invalid file: content/home.php
#0 C:\xampp\htdocs\opacko\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('content/home.ph...')
#1 C:\xampp\htdocs\opacko\system\Common.php(1097): CodeIgniter\View\View->render('content/home', Array, true)
#2 C:\xampp\htdocs\opacko\app\Controllers\Home.php(23): view('content/home')
#3 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): App\Controllers\Home->home()
#4 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-09-28 11:34:10 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:34:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:34:10 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:34:43 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:34:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:34:43 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:34:58 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:34:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:34:58 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:36:29 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:36:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:36:29 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:43:10 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:43:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'passwordf', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:43:10 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:44:55 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:44:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:44:55 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:49:45 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:49:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:49:45 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:49:53 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:49:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:49:53 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:50:07 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:50:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:50:07 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-09-28 11:51:22 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: NO)
CRITICAL - 2021-09-28 11:51:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
#0 C:\xampp\htdocs\opacko\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\opacko\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\opacko\ion-auth\Models\IonAuthModel.php(898): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', '\xC3\xBAassword', false)
#4 C:\xampp\htdocs\opacko\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\opacko\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-09-28 11:51:22 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\opacko\app\Views\errors\html\error_exception.php(96): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\opacko\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-09-28 11:52:52 --> Invalid file: layout/header_loggedIn.php
#0 C:\xampp\htdocs\opacko\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layout/header_l...')
#1 C:\xampp\htdocs\opacko\system\Common.php(1097): CodeIgniter\View\View->render('layout/header_l...', Array, true)
#2 C:\xampp\htdocs\opacko\app\Controllers\Home.php(16): view('layout/header_l...')
#3 C:\xampp\htdocs\opacko\system\CodeIgniter.php(811): App\Controllers\Home->home()
#4 C:\xampp\htdocs\opacko\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\opacko\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\opacko\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
